export const levelsImgData: any = {
    level1:  'https://web.clydetap.site/img/levels/level-1.png',
    level2:  'https://web.clydetap.site/img/levels/level-2.png',
    level3:  'https://web.clydetap.site/img/levels/level-3.png',
    level4:  'https://web.clydetap.site/img/levels/level-4.png',
    level5:  'https://web.clydetap.site/img/levels/level-5.png',
    level6:  'https://web.clydetap.site/img/levels/level-6.png',
    level7:  'https://web.clydetap.site/img/levels/level-7.png',
    level8:  'https://web.clydetap.site/img/levels/level-8.png',
    level9:  'https://web.clydetap.site/img/levels/level-9.png',
    level10: 'https://web.clydetap.site/img/levels/level-10.png',
    level11: 'https://web.clydetap.site/img/levels/level-11.png',
    level12: 'https://web.clydetap.site/img/levels/level-12.png',
    level13: 'https://web.clydetap.site/img/levels/level-13.png',
    level14: 'https://web.clydetap.site/img/levels/level-14.png',
    level15: 'https://web.clydetap.site/img/levels/level-15.png',
}