export const APP_ENV = import.meta.env.VITE_APP_ENV || 'production';
export const USER_ID = import.meta.env.VITE_USER_ID || 1;
export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000';
export const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || 'http://localhost:4000';
export const SOCKET_PATH = import.meta.env.VITE_SOCKET_PATH;
export const BOT_USERNAME = import.meta.env.VITE_BOT_USERNAME || 'clydetapbot';
export const ADS_GRAM_ID = import.meta.env.ADS_GRAM_ID || '1205';
export const UI_COLOR = '#b58863';
export const UI_COLOR_SECOND = '#f0d9b5';