export const boostImgData: any = {
    pawLg: 'https://web.clydetap.site/img/paw-lg.png',
    question: 'https://web.clydetap.site/img/question.png',
    energyIconLg: 'https://web.clydetap.site/img/energy-icon-lg.png',
    boostIconLg: 'https://web.clydetap.site/img/boost-icon-lg.png',
    coinLevel: 'https://web.clydetap.site/img/coin-level.png',
    arrow: 'https://web.clydetap.site/img/arrow.png',
    multitapIcon: 'https://web.clydetap.site/img/multitap-icon.png',
    multitapLg: 'https://web.clydetap.site/img/multitap-lg.png',
    miningIcon: 'https://web.clydetap.site/img/mining-icon.png',
    miningLg: 'https://web.clydetap.site/img/mining-lg.png',
    boneIcon: 'https://web.clydetap.site/img/bone-icon.png',
    boneLg: 'https://web.clydetap.site/img/bone-icon-lg.png',
    coinIconLg: 'https://web.clydetap.site/img/coin-level.png',
    turboLg: 'https://web.clydetap.site/img/turbo-lg.png',
    closeIcon: 'https://web.clydetap.site/img/close.png',
}